[package]
name = "combination"
version = "0.1.0"
authors = ["shawroger <roger@shawroger.com>"]
edition = "2018"
description = "JSON implementation in Rust"
repository = "https://github.com/shawroger/combination.git"
documentation = "https://docs.rs/json/"
license = "MIT/Apache-2.0"

[dependencies]
